### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by 12people** [xpavle00/Habo#29]
It'd be great to support Habo on Linux too.

I opened up a pull request for this purpose — #28 .

Once that's accepted, I can work on creating a [Flatpak](https://www.flatpak.org/) for this that could be published on [Flathub](https://flathub.org/), a popular app store for Linux.

**Comment by xpavle00** [comment]
Hey, thanks for your contribution. I looked at this and it looks good in Linux. I want to also test it on Mac. 
But maybe it would be nice to add some window size restrictions (https://pub.dev/packages/window_manager) because for now, Habo is not responsive (it was not targeted for other displays than mobile in portrait mode).

**Comment by Shahin-rmz** [comment]
Hello,
Would I please know what is the status of linux version?
Could not find the flatpack.
A self-hosted version will be awesome, as we can serve the app for ourselves.
I have a bit of docker and also python experience. feel free to tell me if there are any tasks.

**Comment by 12people** [comment]
@Shahin-rmz Just noticed your comment.

I haven't found the time to work on a Flatpak build script yet. If this is something you'd like to help me with, let me know, we could arrange a call and I could explain the basics of setting it up.

**Comment by Shahin-rmz** [comment]
Well, yes' I still love to contribute/ help for such project. First of all, I need it for tracking my life. 
But the thing is, at the moment I am working on one full-time and two halftime projects. 
They leave me no time to open a new project.
